# --------------------- #
#   Main Configs
# --------------------- #
url:  http://shaneweng.com
title: Talk about Tech and Business
author: Shane Weng
categories: [blog, blog-tech, blog-biz, blog-live]
permalink: /:categories/:title

twitter: baiyungroup
disqus_shortname: shanewengcom
googleplus: shane.weng@gmail.com
# analytics: UA-45893255-1
analytics: UA-55537228-2

# --------------------- #
#   Jekyll & Plugin 
# --------------------- #

markdown: redcarpet
# pygments: true
highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
