# --------------------- #
#   Main Configs
# --------------------- #
url:  http://swcool.github.io
title: Talk about Tech and Biz
author: Shane Weng

twitter: baiyungroup  
disqus_shortname: swgithub
googleplus: shane.weng@gmail.com

# --------------------- #
#   Jekyll & Plugin 
# --------------------- #

markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
