# --------------------- #
#   Main Configs
# --------------------- #
url:  http://swcool.github.io
addr: swcool.github.io
title: Talk about Tech and Biz
author: Shane Weng
categories: blog coding biz
permalink: /:categories/:title

twitter: baiyungroup  
disqus_shortname: swgithub
googleplus: shane.weng@gmail.com
analytics: UA-44428045-1

# --------------------- #
#   Jekyll & Plugin 
# --------------------- #

markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
