# --------------------- #
#   Main Configs
# --------------------- #
url:  http://swcool.github.io
title: Talk about Tech and Business
author: Shane Weng
categories: [blog, coding, biz]
permalink: /:categories/:title

twitter: baiyungroup
disqus_shortname: shanewengcom
googleplus: shane.weng@gmail.com
analytics: UA-45893255-1

# --------------------- #
#   Jekyll & Plugin 
# --------------------- #

markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
